spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/arblog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: iop654321
logging:
  level:
    root: warn
    com.andyron.arblog: info
  file:
    path: log/
    name: arlog-prod.log
server:
  port: 8081